source 'https://github.com/CocoaPods/Specs.git' # 公有源
source 'https://github.com/NJHu/NJSpecs.git' # NJ 私有源

use_frameworks!

target 'NJMediator_NJNowShow_Example' do
  pod 'NJMediator_NJNowShow', :path => '../'

  target 'NJMediator_NJNowShow_Tests' do
    inherit! :search_paths

    
  end
end
